### ISSUE TITLE
Si la reserva la realiza el admin/staff, que vuelva al listado de reservas

### ISSUE THREAD

**Issue by GilardoniLucio** [DSW-3k02-GGJM/TP-3k02-Berli-Gilardoni-Godoy-Jaca-Marquez-App#11]
Actualmente vuelve a la página de inicio.

**Comment by MatiPoli** [comment]
Se puede hacer. Si te fijás en cómo hice los dialog de confirmar / error le agregué un campo que permite cambiar a dónde te lleva el dialog.
