### ISSUE TITLE
Validación nro DNI/otro exige hacer click dos veces en "Guardar Cambios"

### ISSUE THREAD

**Issue by GilardoniLucio** [DSW-3k02-GGJM/TP-3k02-Berli-Gilardoni-Godoy-Jaca-Marquez-App#14]
Al crear o editar usuario, si se setea un nro de dni invalido, y es el unico campo invalido, al corregirlo el usuario debe apretar dos veces en "Guardar cambios" para que se registren dichos cambios y avance la pantalla.

**Comment by MatiPoli** [comment]
El error era que los validadores se actualizaban con el 'blur'. Siempre tiene que estar en 'submit'.
